# Generated by Django 4.2.7 on 2023-12-17 11:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indexpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='residential_building',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='indexpage.residentialbuilding'),
        ),
        migrations.AlterField(
            model_name='citizen',
            name='apartment',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='indexpage.apartment'),
        ),
        migrations.AlterField(
            model_name='citizen',
            name='passport_data',
            field=models.CharField(max_length=10, validators=[django.core.validators.MaxLengthValidator(10), django.core.validators.MinLengthValidator(10)]),
        ),
        migrations.AlterField(
            model_name='citizen',
            name='phone_number',
            field=models.CharField(max_length=11, validators=[django.core.validators.MaxLengthValidator(11), django.core.validators.MinLengthValidator(11)]),
        ),
        migrations.AlterField(
            model_name='city',
            name='area',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='indexpage.area'),
        ),
        migrations.AlterField(
            model_name='district',
            name='city',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='indexpage.city'),
        ),
        migrations.AlterField(
            model_name='residentialbuilding',
            name='street',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='indexpage.street'),
        ),
        migrations.AlterField(
            model_name='street',
            name='district',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='indexpage.district'),
        ),
    ]
